project:
  type: website
  output-dir: docs
  preview: 
    port: 4220 




website:
  title: "Z. Khalaji Pirbaluti"
  site-url: "https://gazellarium.github.io/" # Replace with your actual site URL
  favicon: content/images/favicon.png # Optional, add a favicon
  description: "A personal website for Z. Khalaji Pirbaluti"  
  google-analytics:
    tracking-id: "G-WCC4REHNM4"
  search: false
  
  
  sidebar:
    style: "docked"
    collapse: false # keep the sidebar always expanded
    pinned: true
    align: left
    collapse-level: 2


    contents: #tabs on the sidebar
    
      - text: "Home"
        href: content/index.qmd
        
      - section: "Academic:"
        contents:
          - text: "Research & Projects"
            href: content/research_project.qmd
          - text: "Useful Resources"
            href: content/resources.qmd
          
      #- section: "Portfolio"
        #contents:
          #- text: "Project1"
          #  href: content/project1.qmd
          #- text: "Project2"
          #  href: content/project2.qmd
                
      - section: "Repositories:"
        contents: 
          - text: "OSF"
            href: https://osf.io/5fshr/
            target: blank
        
          - text: "Github"
            href: https://github.com/gazellarium?tab=repositories
            target: blank
            
          - text: "Shinyapp"
            href: https://gazellarium.shinyapps.io/ssp-exp/
            
          - text: "Tableau Public"
            href: https://public.tableau.com/app/profile/z.khalaji/vizzes
      
    # tools:
    #   - icon: github
    #     href: https://github.com/gazellarium?tab=repositories
    
  
    # Footer
  page-footer:
    center: "&copy; GKP - 06.2025"
  
    

format:
  html:
    theme: 
      light: [flatly, content/styles.scss]
      dark: [darkly, content/styles.scss]
    respect-user-color-scheme: true
    fontsize: 1.1rem
    #css: styles.scss
    toc: true
    grid:
      sidebar-width: 255px
      #body-width:	800px
      margin-width:	200px
      #gutter-width:	1.5em

editor: visual

